=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/examen/ej4/lliga.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- elemento raÃ­z -->
  <xs:element name="lliga">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="jornada" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="partit" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="dia" type="xs:string"/>
  
                    <xs:element name="equip" minOccurs="2" maxOccurs="2">
                      <xs:complexType>
                        <xs:sequence>
      
                          <xs:element name="nom" type="xs:string"/>
                          <xs:element name="resultat" type="xs:integer"/>
                          
                          <xs:element name="gols">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="jugador"  minOccurs="0" maxOccurs="unbounded">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:pattern value="[A-Z]([a-z])*"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          
                        </xs:sequence>
                        <xs:attribute name="juga"> <!-- ATRIBUTO DE EQUIP-->
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:pattern value="local|visitant"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>

                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                  <xs:attribute name="num" type="xs:integer"/> <!-- ATRIBUTO DE PARTIT-->
                </xs:complexType>
              </xs:element>

            </xs:sequence>
            <xs:attribute name="num" type="xs:integer"/> <!-- ATRIBUTO DE JORNADA-->
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/examen/ej4/lliga.xml
<?xml version="1.0" encoding="UTF-8"?>
<lliga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lliga.xsd">
  <jornada num="1">
    <partit num="1">
      <dia>23-12-2010</dia>
      <equip juga="local">
        <nom>F.C. Masarach</nom>
        <resultat>2</resultat>
        <gols>
          <jugador>Palol</jugador>
          <jugador>Palol</jugador>
        </gols>
      </equip>
      <equip juga="visitant">
        <nom>U.E.Cabanes</nom>
        <resultat>0</resultat>
        <gols/>
      </equip>
    </partit>
    <partit num="2">
      <dia>23-12-2010</dia>
      <equip juga="local">
        <nom>C.E.Vilatenim</nom>
        <resultat>1</resultat>
        <gols>
          <jugador>Pinxito</jugador>
        </gols>
      </equip>
      <equip juga="visitant">
        <nom>Reial Vilabertran</nom>
        <resultat>1</resultat>
        <gols>
          <jugador>Moreno</jugador>
        </gols>
      </equip>
    </partit>
  </jornada>
</lliga>


<!-- 
   El valor de l’atribut juga només pot ser: local o visitant.
   Només pot haver-hi dos equips per a cada partit.
   El nom del jugador que ha marcat gol ha de començar sempre amb majúscula.
   Associa correctament el fitxer xml al fitxer xsd (hauràs de pujar tant el lliga.xml com el
  lliga.xsd)
-->
