=== apalaciosdev/DAW1-Tasks/M04/UF1/pt8/ex1/libreria.dtd
<!ELEMENT libreria (libro+)>
<!ELEMENT libro (nombre, fechaPublicacion, numeroEdicion, autor+)>
<!ATTLIST libro categoria (poesia|viajes|novela|cocina) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ELEMENT numeroEdicion (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/pt8/ex1/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "libreria.dtd">


<libreria> 
  <libro categoria="poesia">
    <nombre>Don Quijote de la Mancha</nombre>
    <fechaPublicacion>2010</fechaPublicacion>
    <numeroEdicion>2</numeroEdicion>
    <autor>Cervantes</autor>
  </libro>

  <libro categoria="viajes">
    <nombre>Pepe</nombre>
    <fechaPublicacion>2021</fechaPublicacion>
    <numeroEdicion>1</numeroEdicion>
    <autor>Pepe el Real</autor>
  </libro>
  
  <libro categoria="novela">
    <nombre>Sin tetas no hay paraiso</nombre>
    <fechaPublicacion>2003</fechaPublicacion>
    <numeroEdicion>1</numeroEdicion>
    <autor>Panchito</autor>
  </libro>
  
  <libro categoria="cocina">
    <nombre>Karlos el cocinero</nombre>
    <fechaPublicacion>2020</fechaPublicacion>
    <numeroEdicion>2</numeroEdicion>
    <autor>Karlos</autor>
  </libro>
</libreria>
