=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/repaso/dtd/series.dtd
<!ELEMENT series (serie+)>
<!ELEMENT serie (nombreSerie, sinopsis, numeroTemporadas, fechaPublicacion, director, guinista+, actores, temporadas)>
<!ELEMENT nombreSerie (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT numeroTemporadas (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>

<!ELEMENT director (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT guionista (#PCDATA)>

<!ELEMENT actores (principales, secundarios)>
<!ELEMENT principales (actor+)>
<!ELEMENT secundarios (actor+)>
<!ELEMENT actor (nombreActor, apellidosActor, nombrePersonaje)>
<!ELEMENT nombreActor (#PCDATA)>
<!ELEMENT apellidosActor (#PCDATA)>
<!ELEMENT nombrePersonaje (#PCDATA)>

<!ELEMENT temporadas (temporada+)>
<!ELEMENT temporada (añoEstreno, numeroCapitulos, capitulos)>
<!ATTLIST temporada num CDATA #REQUIRED>
<!ELEMENT añoEstreno (#PCDATA)>
<!ELEMENT numeroCapitulos (#PCDATA)>

<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (nombreCapitulo)>
<!ATTLIST capitulo num CDATA #REQUIRED>
<!ELEMENT nombreCapitulo (#PCDATA)>

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/repaso/dtd/series.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "series.dtd">

<series>
  <serie>
    <nombreSerie></nombreSerie>
    <sinopsis></sinopsis>
    <numeroTemporadas></numeroTemporadas>
    <fechaPublicacion></fechaPublicacion>
    
    <director> <!-- Solo puede haber un director -->
      <nombre></nombre>
      <apellidos></apellidos>
    </director>
    
    <guionista>Pepe</guionista> <!-- Pueden haber varios guinistas -->
    <guionista>Juan</guionista>

    <actores> <!-- Mínimo un actor -->
      <principales>
        <actor>
          <nombreActor>Olga</nombreActor>
          <apellidosActor>Martinez</apellidosActor>
          <nombrePersonaje>Pepa</nombrePersonaje>
        </actor>
        <actor>
          <nombreActor>Maria</nombreActor>
          <apellidosActor>Martinez</apellidosActor>
          <nombrePersonaje>Marta</nombrePersonaje>
        </actor>
      </principales>

      <secundarios>
        <actor>
          <nombreActor>Manolo</nombreActor>
          <apellidosActor>Perez</apellidosActor>
          <nombrePersonaje>Manolo</nombrePersonaje>
        </actor>
        <actor>
          <nombreActor>Aitor</nombreActor>
          <apellidosActor>Fernandez</apellidosActor>
          <nombrePersonaje>Daniel</nombrePersonaje>
        </actor>
      </secundarios>
    </actores>  

    <temporadas> <!-- Atributo num OBLIGATORIO -->
      <temporada num="1">
        <añoEstreno></añoEstreno>
        <numeroCapitulos></numeroCapitulos>
        
        <capitulos>
          <capitulo num="1">
            <nombreCapitulo>Génesis</nombreCapitulo>
          </capitulo>
          <capitulo num="2">
            <nombreCapitulo>Amanecer</nombreCapitulo>
          </capitulo>
        </capitulos>
      </temporada>
      
      <temporada num="2">
        <añoEstreno></añoEstreno>
        <numeroCapitulos></numeroCapitulos>
        
        <capitulos>
          <capitulo num="1">
            <nombreCapitulo>Génesis</nombreCapitulo>
          </capitulo>
          <capitulo num="2">
            <nombreCapitulo>Amanecer</nombreCapitulo>
          </capitulo>
        </capitulos>
      </temporada>
    </temporadas>
  </serie>

</series>
