=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/pt9/b/esquema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- elemento raÃ­z -->
  <xs:element name="taulaPeriodica">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="atoms" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="atom" minOccurs="1" maxOccurs="unbounded">

                <xs:complexType>
                  <xs:sequence>
           
                    <xs:element name="nom">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="50"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <xs:element name="simbol">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="3"/>
                          <xs:pattern value="[A-Z][a-zA-Z]( [A-Z][a-zA-Z])*"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
               
                    <xs:element name="numeroAtomic">
                      <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="118"/>
                      </xs:restriction>
                    </xs:simpleType>
                    </xs:element>
                
                    <xs:element name="pesAtomic">
                      <xs:simpleType>
                        <xs:restriction base="xs:float"/>
                      </xs:simpleType>
                    </xs:element>
  
                    <xs:element name="puntEbullicio">                
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute name="unitats" default="C">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:pattern value="[C|K]"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                 
                    <xs:element name="densitat">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="unitats"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>

                  <xs:attribute name="estat">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="solid|liquid|gaseos"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  
                </xs:complexType>
              </xs:element>      
            </xs:sequence>   
          </xs:complexType>
        </xs:element>        
      </xs:sequence>  
    </xs:complexType>
  </xs:element>
</xs:schema>

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/pt9/b/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<taulaPeriodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
  <atoms>
    <atom estat="gaseos">
      <nom>Hidrogen</nom>
      <simbol>SH</simbol>
      <numeroAtomic>1</numeroAtomic>
      <pesAtomic>1.00794</pesAtomic>
      <puntEbullicio unitats="K">20.28</puntEbullicio>
      <densitat unitats="grams/centímetres  cúbics">0.0899</densitat>
    </atom>
    
    <atom estat="gaseos">
      <nom>Heli</nom>
      <simbol>HE</simbol>
      <numeroAtomic>1</numeroAtomic>
      <pesAtomic>1.00794</pesAtomic>
      <puntEbullicio unitats="K">20.28</puntEbullicio>
      <densitat unitats="grams/centímetres  cúbics">0.0899</densitat>
    </atom>
  </atoms>

  
</taulaPeriodica>
