=== apalaciosdev/DAW1-Tasks/M04/UF1/pt8/ex3/smartphones.dtd
<!ELEMENT smartphones (mobil+)>
<!ELEMENT mobil (nom, sistemaOperatiu, dimensions, pes, resolucioPantalla, processador, memoria, preu)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT sistemaOperatiu (#PCDATA)>
<!ELEMENT dimensions (altura, amplada, profunditat)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT amplada (#PCDATA)>
<!ELEMENT profunditat (#PCDATA)>
<!ELEMENT pes (#PCDATA)>
<!ELEMENT resolucioPantalla (#PCDATA)>
<!ELEMENT processador (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT preu (#PCDATA)>

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/pt8/ex3/smartphones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE smartphones SYSTEM "smartphones.dtd">

<smartphones>
  <mobil>
    <nom>asdasd</nom>
    <sistemaOperatiu>sdfsd</sistemaOperatiu>
    <dimensions>
      <altura>123</altura>
      <amplada>1234</amplada>
      <profunditat>234</profunditat>
    </dimensions>
    <pes>sdf</pes>
    <resolucioPantalla>213</resolucioPantalla>
    <processador>asdasd</processador>
    <memoria>128</memoria>
    <preu>1300</preu>
  </mobil>
  
  <mobil>
    <nom>asdasd</nom>
    <sistemaOperatiu>sdfsd</sistemaOperatiu>
    <dimensions>
      <altura>123</altura>
      <amplada>1234</amplada>
      <profunditat>234</profunditat>
    </dimensions>
    <pes>sdf</pes>
    <resolucioPantalla>213</resolucioPantalla>
    <processador>asdasd</processador>
    <memoria>128</memoria>
    <preu>1300</preu>
  </mobil>
</smartphones>
