=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/repaso/xsd/esquema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- elemento raÃ­z -->
  <xs:element name="tablaPeriodica">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="atomos" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="atomo" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="nombre"/>
                    
                    <xs:element name="simbolo">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="3"/>
                          <xs:pattern value="[A-Z][a-zA-Z]( [A-Z][a-zA-Z])*"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    
                    <xs:element name="numeroAtomico"/>
                    
                    <xs:element name="pesoAtomico"/>
                    
                    <xs:element name="puntoBullicion"> <!-- CON ATRIBUTO -->               
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute name="unidades" default="C">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:pattern value="[C|K]"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    
                    <xs:element name="densidad"> <!-- CON ATRIBUTO -->               
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute name="unidades"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>

                  <!-- ATRIBUTO DE PADRE-->
                  <xs:attribute name="estado">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="gaseoso|liquido|solido"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>

                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>


      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/repaso/xsd/tabla_periodica.xml
<?xml version="1.0" encoding="UTF-8"?>

<tablaPeriodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
  <atomos>
    <atomo estado="gaseoso">
      <nombre>Hidrógeno</nombre>
      <simbolo>H</simbolo>
      <numeroAtomico>1</numeroAtomico>
      <pesoAtomico>1,00794</pesoAtomico>
      <puntoBullicion unidades="kelvin">20,28</puntoBullicion>
      <densidad unidades="gramos">0,0899</densidad>
    </atomo>
    
    <atomo estado="gaseoso">
      <nombre>Hidrógeno</nombre>
      <simbolo>H</simbolo>
      <numeroAtomico>1</numeroAtomico>
      <pesoAtomico>1,00794</pesoAtomico>
      <puntoBullicion unidades="kelvin">20,28</puntoBullicion>
      <densidad unidades="gramos">0,0899</densidad>
    </atomo>
  </atomos>
</tablaPeriodica>
