=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/pt9/a/esquema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- elemento raÃ­z -->
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:all>

        <!-- hijos de biblioteca  [web & llibres]-->

        <!-- [web] -->
        <xs:element name="web" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nomWeb"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>


        <!-- [llibres] -->
        <xs:element name="llibres" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>


              <!-- hijos de llibres -->
              <xs:element name="llibre" minOccurs="1" maxOccurs="unbounded">

                <xs:complexType>
                  <xs:sequence>
                    <!-- elemento autor -->
                    <xs:element name="autor">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="50"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <!-- elemento titulo -->
                    <xs:element name="titol">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="50"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>


                  <!-- atributo codigo -->
                  <xs:attribute name="codi">
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="9999"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>

                  <!-- atributo ubicacio -->
                  <xs:attribute name="ubicacio">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="estanteria 1|estanteria 2|estanteria 3|estanteria 4|estanteria 5|estanteria 6|estanteria 7|estanteria 8|estanteria 9|estanteria 10|estanteria 11|estanteria 12|estanteria 13|estanteria 14"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>


                </xs:complexType>
              </xs:element>      <!-- FIN de llibre -->

            </xs:sequence>   
          </xs:complexType>
        </xs:element>        <!-- FIN de [llibres] -->


      </xs:all>   <!-- FIN hijos de biblioteca -->
    </xs:complexType>
  </xs:element>

  <xs:element name="llibre">

  </xs:element>




</xs:schema>

<!-- minInclusive -->

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/pt9/a/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
  <llibres>
    <llibre codi="1" ubicacio="estanteria 3">
      <autor>Miguel Hernandez</autor>
      <titol>Obra poètica completa</titol>
    </llibre>
    <llibre codi="3" ubicacio="estanteria 4">
      <autor>Miguel Hernandez</autor>
      <titol>Obra poètica completa</titol>
    </llibre>
  </llibres>
  <web>sis</web>
</biblioteca>
