=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/examen/ej3/nba.dtd
<!ELEMENT nba (equip+)>

<!ELEMENT equip (nomCiutat, nomEquip, staffTecnic, plantilla)>
<!ATTLIST equip sigles CDATA #REQUIRED>

<!ELEMENT nomCiutat (#PCDATA)>
<!ELEMENT nomEquip (#PCDATA)>

<!ELEMENT staffTecnic (entrenador, asistent*)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT asistent (#PCDATA)>

<!ELEMENT plantilla (jugador+)>
<!ELEMENT jugador (nom, dorsal, sou)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT dorsal (#PCDATA)>
<!ELEMENT sou (#PCDATA)>








<!-- 
 L’atribut sigles del element equip es obligatori.
 La plantilla pot contenir més d’un jugador.
 staffTecnic només pot tenir un entrenador i l’asistent és opcional.

-->

=== apalaciosdev/DAW1-Tasks/M04 - HTML&CSS/UF1/examen/ej3/nba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nba SYSTEM "nba.dtd">
<nba>
  <equip sigles="LAK">
    <nomCiutat>Los Angeles</nomCiutat>
    <nomEquip>Lakers</nomEquip>
    <staffTecnic>
      <entrenador>Frank Vogel</entrenador>
      <asistent>David Fizdale</asistent>
    </staffTecnic>
    <plantilla>
      <jugador>
        <nom>Lebron James</nom>
        <dorsal>23</dorsal>
        <sou>2.000.000$</sou>
      </jugador>
      <!-- ... Podriem afegir tants jugadors com necessitessim -->
    </plantilla>
  </equip>
  <equip sigles="CHI">
    <nomCiutat>Chicago</nomCiutat>
    <nomEquip>Bulls</nomEquip>
    <staffTecnic>
      <entrenador>Billy Donovan</entrenador>
      <asistent>Maurice Cheeks</asistent>
    </staffTecnic>
    <plantilla>
      <jugador>
        <nom>Lonzo Ball</nom>
        <dorsal>2</dorsal>
        <sou>1.000.000$</sou>
      </jugador>
      <!-- ... Podriem afegir tants jugadors com necessitessim -->
    </plantilla>
  </equip>
  <!-- ... Podriem afegir tants equips com necesitem guardar -->
</nba>
